server:
  port: 8081
spring:
  application:
    name: banking-app
  h2:
    console:
      enabled: true
      settings:
        web-allow-others: true
  datasource:
    url: jdbc:h2:mem:testDB
    username: sa
    password: sa